builds:
  - main: main.go
    binary: release
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwnin: macOS
